### ISSUE TITLE
How to programatically identify holidays?

### ISSUE THREAD

**Issue by brunoais** [svendiedrichsen/jollyday#139]
For my use cases, I want to know, for the country and city it is about, what holiday it is.

For example, I may want to know:

1. When is Pentecost?
2. When is the city-specific holiday?

All that appears to be the output of the API is a `Holiday` object instance that only has a date and a specifier text which may or may not be the holiday I'm looking for.

Help please.

**Comment by svendiedrichsen** [comment]
Hi @brunoais ,

you can use the _propertiesKey_ as an identifier of the holiday if you have to distinguish the holidays. It is rather a key for the description of the holiday but there if no such thing as an id otherwise.

But if you find the API insufficient for your purposes please feel free to propose a solution by PR.

Cheers
Sven

**Comment by brunoais** [comment]
OK Thank you.
